baseURL = "https://recipes.frankschmidt.ca"
languageCode = "en-us"
title = "Recipes"
themesDir = "themes"
theme = "hugo-book"
BookMenuBundle = '/menu'
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
