site_name: 4H Computer Project 
site_url: https://4h.frankschmidt.ca
theme: material 
nav:
  - Home: index.md
  - Project Requirements: work-requirement.md
  - Judging: judging.md
  - Code Academy: codeacademy.md
  - 3D Printing:
    - Thingiverse: thingiverse.md
    - Tinkercad: tinkercad.md
